### ISSUE TITLE
Fix the starting coordinates

### ISSUE THREAD

**Issue by cromanpa94** [cromanpa94/BarrioMap#11]
In the landing page, please use pre-defined coordinates (e.g. Tucson, lat = 32.2540, lon = -111.02). You can set this by using the `value` argument in `textInput()`.

**Comment by rog-SARTHAK** [comment]
#Added value arguments
textInput("latitude", "Latitude", value = 32.2540),
textInput("longitude", "Longitude", value = -110.9742),

**Comment by rog-SARTHAK** [comment]
addressed on commit f62e22f
