### ISSUE TITLE
Remove the `NULL` box in leaflet

### ISSUE THREAD

**Issue by cromanpa94** [cromanpa94/BarrioMap#12]
Remove box located on the top right of the map

<img width="599" alt="image" src="https://user-images.githubusercontent.com/18270508/218512988-43ed2770-1fc3-4899-b68d-f68e1d4225e4.png">

**Comment by rog-SARTHAK** [comment]
Removed line addLayersControl(overlayGroups = c(), options = layersControlOptions(collapsed = FALSE))

**Comment by rog-SARTHAK** [comment]
Null checkbox removed in commit # 4572228
