### ISSUE TITLE
Disable zoom options in the map

### ISSUE THREAD

**Issue by cromanpa94** [cromanpa94/BarrioMap#2]
I'd also disable the zoom option in the map itself as the zoom levels are going to be set directly from the drop down menu

**Comment by cromanpa94** [comment]
@rog-SARTHAK, please comment on the issue with a link to the commit used to solve it and then, close it.

**Comment by rog-SARTHAK** [comment]
output$map <- renderLeaflet({
    leaflet(options = leafletOptions(zoomControl = FALSE))

**Comment by cromanpa94** [comment]
The zoom control option was disabled in commit https://github.com/cromanpa94/OSM.sf.shiny/commit/457222809343724dd046353e0eb41063159c1196. For this, we set `zoomControl = FALSE)` in the `leafletOptions()` within the server.
