### ISSUE TITLE
Use webshot to download a PDF of the map

### ISSUE THREAD

**Issue by cromanpa94** [cromanpa94/BarrioMap#3]
Some relevant information. You will need to pass on the map: https://cran.r-project.org/web/packages/webshot/readme/README.html

**Comment by cromanpa94** [comment]
@rog-SARTHAK please review https://trafficonese.github.io/leaflet.extras2/index.html and https://northlandia.wordpress.com/2016/03/16/printing-in-leaflet/.

**Comment by cromanpa94** [comment]
@sarthakua please make sure that the user can define the size of the exported PDF (e.g. A4) and the PDF is indeed in that dimension.

**Comment by cromanpa94** [comment]
Potentially relevant information:

https://stackoverflow.com/questions/49428073/is-it-possible-to-change-leaflet-map-screenshot-size-in-r-shiny

**Comment by rog-SARTHAK** [comment]
Pre existing issue asked:
https://stackoverflow.com/questions/75142332/how-to-download-pdf-using-leaflet-easyprint-library

**Comment by cromanpa94** [comment]
Back-end export using osmdata
