### ISSUE TITLE
Support layer-based (vector) export

### ISSUE THREAD

**Issue by cromanpa94** [cromanpa94/BarrioMap#5]
Note that webshot is able to generate a PDF...but those files have all layers merged into a single. Can we instead split this and allow for individual layers in the PDF?

**Comment by cromanpa94** [comment]
Some relevant information: https://github.com/SpatialServer/Leaflet.MapboxVectorTile

**Comment by rog-SARTHAK** [comment]
Stamen.Toner is broken. We can use CartoDB.Positron instead.
https://rstudio.github.io/leaflet/basemaps.html

**Comment by cromanpa94** [comment]
https://rdrr.io/cran/mapboxapi/man/get_vector_tiles.html

**Comment by cromanpa94** [comment]
@sarthakua is working on OSMDATA
