### ISSUE TITLE
Enable numeric input for particular scales

### ISSUE THREAD

**Issue by cromanpa94** [cromanpa94/BarrioMap#7]
Allow users to define their particular scale level

**Comment by rog-SARTHAK** [comment]
commit [25ac4b7](https://github.com/cromanpa94/OSM.sf.shiny/commit/25ac4b7573989897b7746f1ab95960a232062172)

Addressed in commit 83596e8

Steps:

Made UI function changes for a Custom box

  #custom text
      conditionalPanel(
        condition = "input.scale == 'custom'",
        textInput("custom_scale", "Enter a custom scale", value=3)
      )

Modified if else statement in observe function.

Set setView of observe function to be the only setView.
