### ISSUE TITLE
Include a LICENSE file and create a README

### ISSUE THREAD

**Issue by cromanpa94** [cromanpa94/BarrioMap#8]
The app will be open source: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by cromanpa94** [comment]
Files were created in this commit: https://github.com/cromanpa94/OSM.sf.shiny/commit/e53dfa6e2d8c80fb5ef4daa2e7873ce555f76eca. @rog-SARTHAK still need to include information on the readme.

**Comment by cromanpa94** [comment]
@rog-SARTHAK use this information (+info from the proposal) to create the README: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes

**Comment by rog-SARTHAK** [comment]
Prepared readme draft in  commit ca89b8
